### PR TITLE
DOCS: more explicit install instructions

### PR DESCRIPTION
**Pull request by ttymck**
**Purpose**
After struggling with the installation, I thought it might be helpful to add some clarification to the installation instructions:

**Changes**
1. Explicitly call out the Ubuntu requirement (the Makefile relies on `apt`). Should this be expanded to include .deb based distro? Or perhaps simply "`apt` is required" will suffice?

2. Explicitly call out Go toolchain requirement.

3. Provide the installation command (`sudo make`) and the verification commands, then explain what the Makefile does
  - I figure most folks may want to just quickly install, and aren't particularly concerned with the steps in the Makefile

**Questions**
1. What is the purpose of these variables?
```
export ODIN_EXEC_ENV=True
export ODIN_MONGODB="mongodb://localhost:27017"
```

Should they be moved prior to the `sudo make` command? They didn't seem to be necessary when I installed.

### CODE REVIEW

**Comment by theycallmemac** [comment]
@ttymck all of this looks good.

To answer your question:

```export ODIN_EXEC_ENV=True```to allow for a correct flow through the engine. Mainly this is used for testing though it's recommended to be set always.

```export ODIN_MONGODB="mongodb://localhost:27017``` is used to tell the engine where of the data store is found.

**Comment by ttymck** [comment]
@theycallmemac 
Thank you for clarifying. It sounds like `ODIN_EXEC_ENV` should default to True and only be set to False during testing?

I am still curious about `ODIN_MONGODB`, I thought the engine uses the data URI in `odin-config.yaml`?

**Comment by theycallmemac** [comment]
The config in the main branch is to reflect how the engine is moving forward. Master isn't regarded as stable, the last stable release, the v1.0.0 release, doesn't have this information in the odin-config.yml file.

Moving forward its unlikely we will need the environment variables except for testing.

**Comment by ttymck** [comment]
> Master isn't regarded as stable

Got it, my mistake! That clears up my confusion.

**Pull request merged**
